### ISSUE TITLE
Stable tag/release

### ISSUE THREAD

**Issue by realcharmer** [pkulak/filtile#2]
Please create a Git tag or release when you consider the source "stable" for the purpose of packaging. I'd like to write a package for Void, which requires a stable release to be considered for merge.

Also thanks for writing Filtile, it works well so far.

**Comment by pkulak** [comment]
Ah yeah, never got around to that. I'll dog-food it for a couple more days, just to make sure there aren't any egregious bugs, and then I'll get a release out.

**Comment by realcharmer** [comment]
Sure thing, cheers!

**Comment by pkulak** [comment]
Fixed by: https://github.com/pkulak/filtile/commit/24af59ab78cb4ff1b8fe064c9918fd1edbfdd5f0

**Comment by realcharmer** [comment]
Thanks! A package for Void is now waiting for merge: https://github.com/void-linux/void-packages/pull/48559

**Comment by pkulak** [comment]
Ooo, nice. Thanks for submitting it!
