### ISSUE TITLE
[feature request] - re-implement main location top|bottom options for vertical outputs

### ISSUE THREAD

**Issue by vide0hanz** [pkulak/filtile#4]
Filtile's ability to configure layout options per monitor/output is a feature I feel is missing in rivertile. Unfortunately, filtile is also missing the ability to configure the main-location to anything other than left | right.

I'm imagining something like `filtile main-location top --output DP-2` to allow users to automatically set their preferred location when river initializes. What do you think?

**Comment by pkulak** [comment]
Agreed; this should get done. It's a pretty glaring omission.

**Comment by pkulak** [comment]
Fixed by https://github.com/pkulak/filtile/commit/3d0d688523e3e49be176a34af07159e406da6ee5

**Comment by vide0hanz** [comment]
Thank you! Finally got around to testing this, works great.
