### ISSUE TITLE
Increase/decrese the number of views in the main area?

### ISSUE THREAD

**Issue by vide0hanz** [pkulak/filtile#5]
I'm gonna wager a guess that this was another feature you omitted from rivertile because you didn't use it 😄 

That said, it is very handy to be able to increase the number of views in the main area. This effectively can be used to create a grid layout on-demand when the stack area gets cluttered and the user needs to view more than 3 windows simultaneously. Is it simple to add this in filtile too?

This, combined with what filtile already does (great work btw!) would be a near-perfect replacement for rivertile in my opinion.

**Comment by pkulak** [comment]
> I'm gonna wager a guess that this was another feature you omitted from rivertile because you didn't use it 😄

Haha, you guessed it! I'll see what I can do about adding it in though. At this point I think it's the only feature missing, so it would be cool to add it, and then be able to say this is a drop-in rivertile replacement.

**Comment by pkulak** [comment]
Fixed by https://github.com/pkulak/filtile/commit/e577dbf4c2c1a3adb8277ab9af42e758ffcc3deb

**Comment by darmstrong8008** [comment]
Much appreciated!

**Comment by vide0hanz** [comment]
Thank you!
