### ISSUE TITLE
Switch to gap concept from padding concept

### ISSUE THREAD

**Issue by Brixy** [pkulak/filtile#6]
Hi and thank you very much for filtile. It does everything I would have suggested for rivertile. Excellent!

If it makes sense to you, would you consider switching to a gap-concept instead of padding. Basically it means that you only have gaps between windows but not around them, so the don’t add up – and optionally around the whole layout area.

IMHO this is somewhat saner, easier to understand and looks better. This is comparable to CSS grid gaps.

I looked around a bit. [Rivercarro](https://git.sr.ht/~novakane/rivercarro) uses gaps.

Thanks.

**Comment by pkulak** [comment]
I kinda like padding, and it keeps it consistent with rivertile. It's a minor goal to have this be a drop-in replacement, and it's there except for startup parameters, which would be pretty easy to add once I get around to it. Plus, you can't hide borders, so having zero outer gap generally looks terrible. You can still do that, if you want, when there's one window, with `smart-padding 0`.

**Comment by Brixy** [comment]
Thank you very much for your reply.

You are right: Switching to filtile from rivertile was a breeze.

I’ll just use `smart-padding 0`.

Let me just close this issue.

Thanks again for filtile. It’s an absolutely perfect fit for my river workflow.
