### ISSUE TITLE
Layout name is always "[]="

### ISSUE THREAD

**Issue by Cwmcmahon** [pkulak/filtile#7]
Just switched to filtile from rivercarro, and I'm really liking it! One issue I'm running into is that the layout name is always ```[]=``` regardless of the current layout. The layout name shows up like that in my waybar river/layout module, and in the output of river-bedload as well. This is the output of ```river-bedload -print layout```:
```
[
	{
		"output": "eDP-1",
		"layout": "[]="
	}
]
```
```river-bedload -watch layout``` still updates whenever I switch the layout, but the output is the same. I'm not familiar with Rust yet, so I don't know what the cause might be. 
Also, thank you for making this a flake!

**Comment by pkulak** [comment]
Haha, yeah, I totally forgot to stop hard-coding that at some point.

What do you think about just using arrows, like this?

https://github.com/pkulak/filtile/tree/ISSUE-7

**Comment by Cwmcmahon** [comment]
I like that 👍
Monocle might need a symbol too, and I was thinking that ◎ could be good

**Comment by pkulak** [comment]
Good idea!

**Comment by pkulak** [comment]
Closed with https://github.com/pkulak/filtile/commit/ec9fbe26ce9e493ccd1e35f9fee74bdf30a637f1
