### ISSUE TITLE
`--tags all` not working

### ISSUE THREAD

**Issue by itshog** [pkulak/filtile#8]
Hello, I recently noticed that the `--tags all` flag doesn't work properly. For instance, the command
```
riverctl send-layout-cmd filtile "--tags all view-padding 10"
```
doesn't work, while these work as expected:
```
riverctl send-layout-cmd filtile "view-padding 10"              # current tag
riverctl send-layout-cmd filtile "--tags 1 view-padding 10"     # tag 1     
riverctl send-layout-cmd filtile "--tags 4 view-padding 10"     # tag 3
```
Maybe I'm doing something wrong about the syntax, in which case I'd appreciate being pointed in the right direction.

Thanks in advance.

**Comment by pkulak** [comment]
Oh, nice catch, thank you. I was being really sloppy with the distinction between "no option provided" and "the option of 'all' provided". It _should_ be fixed on master.

**Comment by itshog** [comment]
It seems to be working fine now. Thank you!
